/* Generated by tests/export_digit_weights.py; do not edit. */
#ifndef DIGIT_WEIGHTS_H
#define DIGIT_WEIGHTS_H
#include <stdint.h>
extern const uint32_t conv1_bias_bits[32];
extern const uint32_t conv1_filter_bits[288];
extern const uint32_t conv2_bias_bits[64];
extern const uint32_t conv2_filter_bits[18432];
extern const uint32_t dense_bias_bits[10];
extern const uint32_t dense_filter_bits[92160];
#endif
