"""Export exact float32 constants from the pinned TFLite FlatBuffer."""
import argparse
import hashlib
import struct
from pathlib import Path

from ai_edge_litert import schema_py_generated as schema

EXPECTED_SHA256 = "b0ae6afa9e9bceed8ae3038c0a844634eddc24f30f262c5b7e5ae800db2db50d"
WEIGHTS = (("conv1_bias", 1, 32), ("conv1_filter", 2, 288),
           ("conv2_bias", 3, 64), ("conv2_filter", 4, 18432),
           ("dense_bias", 5, 10), ("dense_filter", 8, 92160))


def export(model_path: Path, output: Path):
    data = model_path.read_bytes()
    digest = hashlib.sha256(data).hexdigest()
    if digest != EXPECTED_SHA256:
        raise ValueError(f"model SHA256 mismatch: {digest}")
    model = schema.Model.GetRootAsModel(data, 0)
    if model.Version() != 3 or model.SubgraphsLength() != 1:
        raise ValueError("unexpected TFLite schema or subgraph count")
    graph = model.Subgraphs(0)
    lines = ["/* Generated by tests/export_digit_weights.py; do not edit. */",
             "#include <stdint.h>", "#include \"digit_weights.h\"", ""]
    for name, index, count in WEIGHTS:
        tensor = graph.Tensors(index)
        if tensor.Type() != schema.TensorType.FLOAT32:
            raise ValueError(f"{name}: expected float32")
        raw = model.Buffers(tensor.Buffer()).DataAsNumpy().tobytes()
        if len(raw) != count * 4:
            raise ValueError(f"{name}: expected {count * 4} bytes, got {len(raw)}")
        words = struct.unpack("<" + "I" * count, raw)
        lines.append(f"const uint32_t {name}_bits[{count}] = {{")
        for start in range(0, count, 8):
            lines.append("    " + ", ".join(f"0x{w:08x}U" for w in words[start:start + 8]) + ",")
        lines.append("};\n")
    output.write_text("\n".join(lines), encoding="ascii")
    header = output.with_name("digit_weights.h")
    header.write_text("/* Generated by tests/export_digit_weights.py; do not edit. */\n"
                      "#ifndef DIGIT_WEIGHTS_H\n#define DIGIT_WEIGHTS_H\n"
                      "#include <stdint.h>\n"
                      + "".join(f"extern const uint32_t {name}_bits[{count}];\n" for name, _, count in WEIGHTS)
                      + "#endif\n", encoding="ascii")
    print(f"model_sha256={digest} exported_float32={sum(x[2] for x in WEIGHTS)}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--model", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    export(args.model, args.output)
